branches:
  only:
    - master
    - dev

language: csharp
mono: none
os: linux
dist: xenial
addons:
  snaps:
    - name: dotnet-sdk
      classic: true
      channel: 5.0/beta
solution: InvestingOak.sln
node_js:
  - "12"
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet restore
  - dotnet build
  - dotnet test
  - cd ClientApp
  - nvm install 12.0
  - nvm use 12.0
  - npm install -g @angular/cli
  - npm rebuild node-sass
  - ng lint
  - ng build --prod
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
