branches:
  only:
    - master
    - dev

language: csharp
mono: none
os: linux
dist: xenial
addons:
  snaps:
    - name: dotnet-sdk
      confinement: classic
      channel: latest/beta
solution: InvestingOak.sln
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet restore
  - dotnet build
  - dotnet test
  - cd ClientApp
  - npm install -g @angular/cli
  - ng lint
  - ng build --prod
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
